In [96]:
# ignore warnings
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

from pydataset import data

import acquire
import prepare

## For all of the models you create, choose a threshold that optimizes for accuracy.

Create a new notebook, logistic_regression, use it to answer the following questions:



In [97]:
titanic = acquire.get_titanic_data()
titanic.head(3)

passenger_id  survived  pclass     sex   age  sibsp  parch     fare  \
0             0         0       3    male  22.0      1      0   7.2500   
1             1         1       1  female  38.0      1      0  71.2833   
2             2         1       3  female  26.0      0      0   7.9250   

  embarked  class deck  embark_town  alone  
0        S  Third  NaN  Southampton      0  
1        C  First    C    Cherbourg      0  
2        S  Third  NaN  Southampton      1

In [98]:
train, validate, test = prepare.clean_titanic(titanic)
train.shape, validate.shape, test.shape

((498, 12), (214, 12), (179, 12))

In [99]:
# SPLIT DATA INTO X AND Y DATA SETS
X_train = train.drop(columns=['survived', 'sex', 'embark_town', 'embark_town_Queenstown', 'embark_town_Southampton', 'sex_male', 'alone', 'sibsp', 'parch'])

X_validate = validate.drop(columns=['survived','sex','embark_town', 'embark_town_Queenstown', 'embark_town_Southampton', 'sex_male', 'alone', 'sibsp', 'parch'])

X_test = test.drop(columns=['survived','sex','embark_town', 'embark_town_Queenstown', 'embark_town_Southampton', 'sex_male', 'alone', 'sibsp', 'parch'])

y_train = train.survived

y_validate = validate.survived 

y_test = test.survived

In [100]:
X_train.head()

pclass   age     fare
271       3  25.0   0.0000
786       3  18.0   7.4958
86        3  16.0  34.3750
353       3  25.0  17.8000
199       2  24.0  13.0000

### 1. Create a model that includes only age, fare, and pclass. Does this model perform better than your baseline?



In [101]:
baseline_accuracy = (train.survived == 0).mean()
baseline_accuracy

0.6164658634538153

In [102]:
# from sklearn.linear_model import LogisticRegression
logit = LogisticRegression(C=1, random_state=123)


In [103]:
logit.fit(X_train, y_train)


LogisticRegression(C=1, random_state=123)

In [104]:
print('Coefficient: \n', logit.coef_)
print('Intercept: \n', logit.intercept_)


Coefficient: 
 [[-0.91716114 -0.03482089  0.00649545]]
Intercept: 
 [2.40727567]


In [105]:
y_pred = logit.predict(X_train)


In [106]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,

In [107]:
y_pred_proba = logit.predict_proba(X_train)


In [108]:
print('Accuracy of Logistic Regression classifier on training set: {:.2f}'
     .format(logit.score(X_train, y_train)))
print(f' Baseline Accuracy is {baseline_accuracy}')
print('The model performed better than the baseline')


Accuracy of Logistic Regression classifier on training set: 0.71
 Baseline Accuracy is 0.6164658634538153
The model performed better than the baseline


In [109]:
print(confusion_matrix(y_train, y_pred))


[[265  42]
 [103  88]]


In [110]:
print(classification_report(y_train, y_pred))


              precision    recall  f1-score   support

           0       0.72      0.86      0.79       307
           1       0.68      0.46      0.55       191

    accuracy                           0.71       498
   macro avg       0.70      0.66      0.67       498
weighted avg       0.70      0.71      0.69       498



### 2. Include sex in your model as well. Note that you'll need to encode or create a dummy variable of this feature before including it in a model.



In [125]:
X_train2 = train.drop(columns=['survived', 'sex', 'embark_town', 'embark_town_Queenstown', 'embark_town_Southampton', 'alone', 'sibsp', 'parch'])

X_validate2= validate.drop(columns=['survived','sex','embark_town', 'embark_town_Queenstown', 'embark_town_Southampton', 'alone', 'sibsp', 'parch'])

X_test2 = test.drop(columns=['survived','sex','embark_town', 'embark_town_Queenstown', 'embark_town_Southampton', 'alone', 'sibsp', 'parch'])

y_train2 = train.survived

y_validate2 = validate.survived 

y_test2 = test.survived

In [112]:
# from sklearn.linear_model import LogisticRegression
logit2 = LogisticRegression(C=1, random_state=123)

In [113]:
logit2.fit(X_train2, y_train)

LogisticRegression(C=1, random_state=123)

In [114]:
print('Coefficient: \n', logit2.coef_)
print('Intercept: \n', logit2.intercept_)

Coefficient: 
 [[-1.16496558e+00 -3.68064104e-02  1.18200217e-03 -2.40812807e+00]]
Intercept: 
 [4.6524267]


In [115]:
y_pred2 = logit2.predict(X_train2)
y_pred2[:5]

array([0, 1, 0, 0, 1])

In [116]:
y_pred_proba2 = logit2.predict_proba(X_train2)
y_pred_proba2

array([[0.8975927 , 0.1024073 ],
       [0.37663055, 0.62336945],
       [0.85801125, 0.14198875],
       [0.89564249, 0.10435751],
       [0.18930879, 0.81069121],
       [0.8662231 , 0.1337769 ],
       [0.86176001, 0.13823999],
       [0.47788258, 0.52211742],
       [0.91255795, 0.08744205],
       [0.52348753, 0.47651247],
       [0.87439661, 0.12560339],
       [0.91110242, 0.08889758],
       [0.92618347, 0.07381653],
       [0.83000806, 0.16999194],
       [0.26686284, 0.73313716],
       [0.48298579, 0.51701421],
       [0.90652825, 0.09347175],
       [0.80143658, 0.19856342],
       [0.93395433, 0.06604567],
       [0.91118137, 0.08881863],
       [0.83716457, 0.16283543],
       [0.14496611, 0.85503389],
       [0.52046451, 0.47953549],
       [0.78788582, 0.21211418],
       [0.88971781, 0.11028219],
       [0.55303237, 0.44696763],
       [0.24201696, 0.75798304],
       [0.06283185, 0.93716815],
       [0.92099015, 0.07900985],
       [0.76345576, 0.23654424],
       [0.

In [117]:
print('Accuracy of Logistic Regression classifier on training set: {:.2f}'
     .format(logit2.score(X_train2, y_train)))
print(f' Baseline Accuracy is {baseline_accuracy}')
print('The model performed better than the baseline and the 1st model without sex')

Accuracy of Logistic Regression classifier on training set: 0.78
 Baseline Accuracy is 0.6164658634538153
The model performed better than the baseline and the 1st model without sex


### 3. Try out other combinations of features and models.



In [118]:
X_train3 = train.drop(columns=['survived', 'sex', 'embark_town'])

X_validate3= validate.drop(columns=['survived', 'sex', 'embark_town'])

X_test3 = test.drop(columns=['survived', 'sex', 'embark_town'])

y_train = train.survived

y_validate = validate.survived 

y_test = test.survived

In [119]:
logit3 = LogisticRegression(C=1, random_state=123)
logit3.fit(X_train3, y_train)

y_pred3 = logit3.predict(X_train3)
y_pred_proba3    = logit3.predict_proba(X_train3)

In [120]:
print('Accuracy of Logistic Regression classifier on training set: {:.2f}'
     .format(logit3.score(X_train3, y_train)))
print(f' Baseline Accuracy is {baseline_accuracy}')
print('The model performed better than the baseline and has all features')

Accuracy of Logistic Regression classifier on training set: 0.80
 Baseline Accuracy is 0.6164658634538153
The model performed better than the baseline and has all features


### 4. Use you best 3 models to predict and evaluate on your validate sample.



In [121]:
y_pred_validate = logit.predict(X_validate)
y_pred_validate2 = logit2.predict(X_validate2)
y_pred_validate3 = logit3.predict(X_validate3)

In [126]:
print("Model 1: solver = lbfgs, c = 1")

print('Accuracy: {:.2f}'.format(logit.score(X_validate, y_validate)))

print(classification_report(y_validate, y_pred_validate))

print('--------------------------------------------------')

print("Model 2: solver = lbfgs, c = 1")

print('Accuracy: {:.2f}'.format(logit2.score(X_validate2, y_validate)))

print(classification_report(y_validate, y_pred_validate2))

print('--------------------------------------------------')

print("Model 3: solver = lbfgs, c = 1")

print('Accuracy: {:.2f}'.format(logit3.score(X_validate3, y_validate)))

print(classification_report(y_validate, y_pred_validate3))

Model 1: solver = lbfgs, c = 1
Accuracy: 0.69
              precision    recall  f1-score   support

           0       0.70      0.87      0.77       132
           1       0.65      0.39      0.49        82

    accuracy                           0.69       214
   macro avg       0.68      0.63      0.63       214
weighted avg       0.68      0.69      0.66       214

--------------------------------------------------
Model 2: solver = lbfgs, c = 1
Accuracy: 0.79
              precision    recall  f1-score   support

           0       0.82      0.84      0.83       132
           1       0.73      0.71      0.72        82

    accuracy                           0.79       214
   macro avg       0.78      0.77      0.78       214
weighted avg       0.79      0.79      0.79       214

--------------------------------------------------
Model 3: solver = lbfgs, c = 1
Accuracy: 0.79
              precision    recall  f1-score   support

           0       0.81      0.86      0.84       1

### 5. Choose you best model from the validation performation, and evaluate it on the test dataset. How do the performance metrics compare to validate? to train?

In [127]:
y_pred_test2 = logit2.predict(X_test2)

In [128]:
print("Model 2: solver = lbfgs, c = 1")

print('Accuracy: {:.2f}'.format(logit2.score(X_test2, y_test)))

print(classification_report(y_test, y_pred_test2))

Model 2: solver = lbfgs, c = 1
Accuracy: 0.82
              precision    recall  f1-score   support

           0       0.88      0.83      0.85       110
           1       0.75      0.81      0.78        69

    accuracy                           0.82       179
   macro avg       0.81      0.82      0.81       179
weighted avg       0.83      0.82      0.82       179

